In [1]:
# Import dependencies
import pandas as pd

In [4]:
# Read in the csv file
counties_df = pd.read_csv('../counties.timeseries.csv')
counties_df

,date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,...,actuals.hsaIcuBeds.currentUsageCovid,metrics.bedsWithCovidPatientsRatio,hsaName,actuals.hospitalBeds.weeklyCovidAdmissions,actuals.hsaHospitalBeds.weeklyCovidAdmissions,metrics.weeklyCovidAdmissionsPer100k,communityLevels.cdcCommunityLevel,communityLevels.canCommunityLevel,actuals.vaccinationsFall2022BivalentBooster,metrics.vaccinationsFall2022BivalentBoosterRatio
0,2020-04-09,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-04-10,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-04-11,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-04-12,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-04-13,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3392913,2023-01-27,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,...,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,0.0,NaN,NaN
3392914,2023-01-28,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,...,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,0.0,NaN,NaN
3392915,2023-01-29,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,...,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,0.0,NaN,NaN
3392916,2023-01-30,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,...,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,0.0,NaN,NaN
3392917,2023-01-31,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,NaN,22.0,...,NaN,NaN,"Weston, WY",NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [5]:
pd.set_option('display.max_rows', 70)
counties_df.dtypes

date                                                 object
country                                              object
state                                                object
county                                               object
fips                                                  int64
lat                                                 float64
long                                                float64
locationId                                           object
actuals.cases                                       float64
actuals.deaths                                      float64
actuals.positiveTests                               float64
actuals.negativeTests                               float64
actuals.contactTracers                              float64
actuals.hospitalBeds.capacity                       float64
actuals.hospitalBeds.currentUsageTotal              float64
actuals.hospitalBeds.currentUsageCovid              float64
unused1                                             float64
actuals.icuBeds.capacity                            float64
actuals.icuBeds.currentUsageTotal                   float64
actuals.icuBeds.currentUsageCovid                   float64
unused2                                             float64
actuals.newCases                                    float64
actuals.vaccinesDistributed                         float64
actuals.vaccinationsInitiated                       float64
actuals.vaccinationsCompleted                       float64
metrics.testPositivityRatio                         float64
metrics.testPositivityRatioDetails                  float64
metrics.caseDensity                                 float64
metrics.contactTracerCapacityRatio                  float64
metrics.infectionRate                               float64
metrics.infectionRateCI90                           float64
unused3                                             float64
unused4                                             float64
metrics.icuCapacityRatio                            float64
riskLevels.overall                                    int64
metrics.vaccinationsInitiatedRatio                  float64
metrics.vaccinationsCompletedRatio                  float64
actuals.newDeaths                                   float64
actuals.vaccinesAdministered                        float64
riskLevels.caseDensity                                int64
cdcTransmissionLevel                                  int64
actuals.vaccinationsAdditionalDose                  float64
metrics.vaccinationsAdditionalDoseRatio             float64
metrics.weeklyNewCasesPer100k                       float64
hsa                                                 float64
hsaPopulation                                       float64
actuals.hsaHospitalBeds.capacity                    float64
actuals.hsaHospitalBeds.currentUsageTotal           float64
actuals.hsaHospitalBeds.currentUsageCovid           float64
actuals.hsaIcuBeds.capacity                         float64
actuals.hsaIcuBeds.currentUsageTotal                float64
actuals.hsaIcuBeds.currentUsageCovid                float64
metrics.bedsWithCovidPatientsRatio                  float64
hsaName                                              object
actuals.hospitalBeds.weeklyCovidAdmissions          float64
actuals.hsaHospitalBeds.weeklyCovidAdmissions       float64
metrics.weeklyCovidAdmissionsPer100k                float64
communityLevels.cdcCommunityLevel                   float64
communityLevels.canCommunityLevel                   float64
actuals.vaccinationsFall2022BivalentBooster         float64
metrics.vaccinationsFall2022BivalentBoosterRatio    float64
dtype: object

In [6]:
# Get the length of each column
counties_df.count()

date                                                3392918
country                                             3392918
state                                               3392918
county                                              3392918
fips                                                3392918
lat                                                       0
long                                                      0
locationId                                          3392918
actuals.cases                                       3321990
actuals.deaths                                      3252706
actuals.positiveTests                                  1057
actuals.negativeTests                                  1060
actuals.contactTracers                                  614
actuals.hospitalBeds.capacity                        347895
actuals.hospitalBeds.currentUsageTotal               343805
actuals.hospitalBeds.currentUsageCovid               235169
unused1                                                   0
actuals.icuBeds.capacity                             219848
actuals.icuBeds.currentUsageTotal                    200769
actuals.icuBeds.currentUsageCovid                    140297
unused2                                                   0
actuals.newCases                                    3295508
actuals.vaccinesDistributed                               0
actuals.vaccinationsInitiated                       1668833
actuals.vaccinationsCompleted                       1683290
metrics.testPositivityRatio                         2599035
metrics.testPositivityRatioDetails                        0
metrics.caseDensity                                 3329622
metrics.contactTracerCapacityRatio                      612
metrics.infectionRate                               3166832
metrics.infectionRateCI90                           3166832
unused3                                                   0
unused4                                                   0
metrics.icuCapacityRatio                             199810
riskLevels.overall                                  3392918
metrics.vaccinationsInitiatedRatio                  1670622
metrics.vaccinationsCompletedRatio                  1683290
actuals.newDeaths                                   3234380
actuals.vaccinesAdministered                          83379
riskLevels.caseDensity                              3392918
cdcTransmissionLevel                                3392918
actuals.vaccinationsAdditionalDose                   705161
metrics.vaccinationsAdditionalDoseRatio              705161
metrics.weeklyNewCasesPer100k                       3329622
hsa                                                 3390677
hsaPopulation                                       3390677
actuals.hsaHospitalBeds.capacity                     452260
actuals.hsaHospitalBeds.currentUsageTotal            452159
actuals.hsaHospitalBeds.currentUsageCovid            421223
actuals.hsaIcuBeds.capacity                          428150
actuals.hsaIcuBeds.currentUsageTotal                 417166
actuals.hsaIcuBeds.currentUsageCovid                 352391
metrics.bedsWithCovidPatientsRatio                   439166
hsaName                                             3390677
actuals.hospitalBeds.weeklyCovidAdmissions           136066
actuals.hsaHospitalBeds.weeklyCovidAdmissions        314367
metrics.weeklyCovidAdmissionsPer100k                 360717
communityLevels.cdcCommunityLevel                    157646
communityLevels.canCommunityLevel                   2729534
actuals.vaccinationsFall2022BivalentBooster           30679
metrics.vaccinationsFall2022BivalentBoosterRatio      30679
dtype: int64

In [7]:
# Create the list of columns to drop
columns_to_drop = ['country', 'lat', 'long', 'actuals.positiveTests', 'actuals.negativeTests', 
                   'actuals.contactTracers', 'unused1', 'unused2', 'actuals.vaccinesDistributed', 
                   'metrics.testPositivityRatio', 'metrics.testPositivityRatioDetails', 'metrics.caseDensity', 
                   'metrics.contactTracerCapacityRatio', 'metrics.infectionRate', 'metrics.infectionRateCI90', 
                   'unused3', 'unused4', 'metrics.icuCapacityRatio', 'riskLevels.overall', 
                   'metrics.vaccinationsInitiatedRatio', 'metrics.vaccinationsCompletedRatio', 
                   'actuals.vaccinesAdministered','riskLevels.caseDensity', 
                   'metrics.vaccinationsAdditionalDoseRatio', 'metrics.weeklyNewCasesPer100k', 'hsa', 
                   'hsaPopulation', 'metrics.bedsWithCovidPatientsRatio', 
                   'hsaName', 'metrics.weeklyCovidAdmissionsPer100k', 'communityLevels.cdcCommunityLevel', 
                   'communityLevels.canCommunityLevel', 'actuals.vaccinationsFall2022BivalentBooster',
                   'metrics.vaccinationsFall2022BivalentBoosterRatio']

In [8]:
# Drop the columns
counties_dropped = counties_df.drop(columns_to_drop, axis=1)
counties_dropped

,date,state,county,fips,locationId,actuals.cases,actuals.deaths,actuals.hospitalBeds.capacity,actuals.hospitalBeds.currentUsageTotal,actuals.hospitalBeds.currentUsageCovid,...,cdcTransmissionLevel,actuals.vaccinationsAdditionalDose,actuals.hsaHospitalBeds.capacity,actuals.hsaHospitalBeds.currentUsageTotal,actuals.hsaHospitalBeds.currentUsageCovid,actuals.hsaIcuBeds.capacity,actuals.hsaIcuBeds.currentUsageTotal,actuals.hsaIcuBeds.currentUsageCovid,actuals.hospitalBeds.weeklyCovidAdmissions,actuals.hsaHospitalBeds.weeklyCovidAdmissions
0,2020-04-09,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-04-10,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-04-11,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-04-12,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-04-13,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3392913,2023-01-27,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3392914,2023-01-28,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3392915,2023-01-29,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3392916,2023-01-30,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3392917,2023-01-31,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,NaN,22.0,NaN,NaN,NaN,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Verify count()
counties_dropped.count()

date                                             3392918
state                                            3392918
county                                           3392918
fips                                             3392918
locationId                                       3392918
actuals.cases                                    3321990
actuals.deaths                                   3252706
actuals.hospitalBeds.capacity                     347895
actuals.hospitalBeds.currentUsageTotal            343805
actuals.hospitalBeds.currentUsageCovid            235169
actuals.icuBeds.capacity                          219848
actuals.icuBeds.currentUsageTotal                 200769
actuals.icuBeds.currentUsageCovid                 140297
actuals.newCases                                 3295508
actuals.vaccinationsInitiated                    1668833
actuals.vaccinationsCompleted                    1683290
actuals.newDeaths                                3234380
cdcTransmissionLevel                             3392918
actuals.vaccinationsAdditionalDose                705161
actuals.hsaHospitalBeds.capacity                  452260
actuals.hsaHospitalBeds.currentUsageTotal         452159
actuals.hsaHospitalBeds.currentUsageCovid         421223
actuals.hsaIcuBeds.capacity                       428150
actuals.hsaIcuBeds.currentUsageTotal              417166
actuals.hsaIcuBeds.currentUsageCovid              352391
actuals.hospitalBeds.weeklyCovidAdmissions        136066
actuals.hsaHospitalBeds.weeklyCovidAdmissions     314367
dtype: int64

In [10]:
# Drop any null values and verify columns lengths
counties_cleaned = counties_dropped.dropna()
counties_cleaned.count()

date                                             21848
state                                            21848
county                                           21848
fips                                             21848
locationId                                       21848
actuals.cases                                    21848
actuals.deaths                                   21848
actuals.hospitalBeds.capacity                    21848
actuals.hospitalBeds.currentUsageTotal           21848
actuals.hospitalBeds.currentUsageCovid           21848
actuals.icuBeds.capacity                         21848
actuals.icuBeds.currentUsageTotal                21848
actuals.icuBeds.currentUsageCovid                21848
actuals.newCases                                 21848
actuals.vaccinationsInitiated                    21848
actuals.vaccinationsCompleted                    21848
actuals.newDeaths                                21848
cdcTransmissionLevel                             21848
actuals.vaccinationsAdditionalDose               21848
actuals.hsaHospitalBeds.capacity                 21848
actuals.hsaHospitalBeds.currentUsageTotal        21848
actuals.hsaHospitalBeds.currentUsageCovid        21848
actuals.hsaIcuBeds.capacity                      21848
actuals.hsaIcuBeds.currentUsageTotal             21848
actuals.hsaIcuBeds.currentUsageCovid             21848
actuals.hospitalBeds.weeklyCovidAdmissions       21848
actuals.hsaHospitalBeds.weeklyCovidAdmissions    21848
dtype: int64

In [34]:
# Save counties_cleaned
#counties_cleaned.to_csv("counties_cleaned.csv", sep=',', header=True, encoding='utf-8')

In [11]:
# Get the completed dtypes for the ERD schema
counties_cleaned.dtypes

date                                              object
state                                             object
county                                            object
fips                                               int64
locationId                                        object
actuals.cases                                    float64
actuals.deaths                                   float64
actuals.hospitalBeds.capacity                    float64
actuals.hospitalBeds.currentUsageTotal           float64
actuals.hospitalBeds.currentUsageCovid           float64
actuals.icuBeds.capacity                         float64
actuals.icuBeds.currentUsageTotal                float64
actuals.icuBeds.currentUsageCovid                float64
actuals.newCases                                 float64
actuals.vaccinationsInitiated                    float64
actuals.vaccinationsCompleted                    float64
actuals.newDeaths                                float64
cdcTransmissionLevel                               int64
actuals.vaccinationsAdditionalDose               float64
actuals.hsaHospitalBeds.capacity                 float64
actuals.hsaHospitalBeds.currentUsageTotal        float64
actuals.hsaHospitalBeds.currentUsageCovid        float64
actuals.hsaIcuBeds.capacity                      float64
actuals.hsaIcuBeds.currentUsageTotal             float64
actuals.hsaIcuBeds.currentUsageCovid             float64
actuals.hospitalBeds.weeklyCovidAdmissions       float64
actuals.hsaHospitalBeds.weeklyCovidAdmissions    float64
dtype: object

In [28]:
# Creating a new DF with just the full columns
counties_dropped2 = counties_dropped[['date', 'state', 'county', 'fips', 'locationId', 'actuals.cases', 
                                      'actuals.deaths', 'actuals.newCases', 'actuals.newDeaths', 
                                      'cdcTransmissionLevel']]
counties_dropped2

,date,state,county,fips,locationId,actuals.cases,actuals.deaths,actuals.newCases,actuals.newDeaths,cdcTransmissionLevel
0,2020-04-09,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,0
1,2020-04-10,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,0
2,2020-04-11,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,0
3,2020-04-12,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,0
4,2020-04-13,AK,Aleutians East Borough,2013,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...
3392913,2023-01-27,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,0.0,0.0,2
3392914,2023-01-28,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,0.0,0.0,2
3392915,2023-01-29,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,0.0,0.0,2
3392916,2023-01-30,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,1885.0,22.0,0.0,0.0,2
3392917,2023-01-31,WY,Weston County,56045,iso1:us#iso2:us-wy#fips:56045,NaN,22.0,NaN,0.0,2

In [29]:
# Drop any null values and verify columns lengths
counties_cleaned2 = counties_dropped2.dropna()
counties_cleaned2.count()

date                    3203737
state                   3203737
county                  3203737
fips                    3203737
locationId              3203737
actuals.cases           3203737
actuals.deaths          3203737
actuals.newCases        3203737
actuals.newDeaths       3203737
cdcTransmissionLevel    3203737
dtype: int64

In [35]:
# Save counties_cleaned2
counties_cleaned2.to_csv("counties_cleaned2.csv", sep=',', header=True, encoding='utf-8')